changed order of rotate_solid and compound creation
ukaea/paramak pull request #781
Opened 2021-03-17 17:29 UTC by billingsley-john

## Proposed changes

PR to fix tf coil bug outlined in #780. Thanks @katie-taylor for raising the issue.
Previously, the outer tf coil and inboard leg were created separately and then made into a single compound before being passed to rotate_solid which placed a shape at each azimuth_placement_angle and unioned. CadQuery didn't like the compound being passed to rotate_solid.
Now, the outer tf coil and inboard leg are passed to rotate_solid separately to place at each azimuthal placement angle and a compound of their shapes created after.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-03-18 09:11 UTC, billingsley-john commented
Inner and outer shapes now cut independently by cutting wedge before being combined in compound

2021-03-19 09:08 UTC, RemDelaporteMathurin requested changes
@billingsley-john Great fix!  Would it be possible to add a test to `TFCoilRectangle()` that would've caught that bug ? and perhaps to the other shapes that have a `inner_leg=True` flag ?

2021-03-19 10:41 UTC, billingsley-john commented
> @billingsley-john Great fix! Would it be possible to add a test to `TFCoilRectangle()` that would've caught that bug ? and perhaps to the other shapes that have a `inner_leg=True` flag ?

Yes, tests will be added and fixes to the other tf coils with the same issue will be made in a future PR by @katie-taylor

2021-03-19 10:47 UTC, RemDelaporteMathurin approved these changes

2021-03-19 12:02 UTC, billingsley-john commented
@RemDelaporteMathurin - Test to catch this error has been added. Similar tests will be added to other tf coil components when fixing those.

2021-03-19 16:26 UTC, merged